#+TITLE: My Emacs Configuration 
#+AUTHOR: Yu Liu


I've been using emacs since 2004 and my .emacs has been growing longer
and longer without the clean organization I wished. Since emacs,
especially org-mode, has been growing into an integral part of my daily
work, I set off to tackle the long existing issue of a messy .emacs
file.

I learned that one could use org-mode to author and organize his emacs
setting in an org file, and load it with org-babel in init.el. In org
file, all the settings will be encapsulated into Lisp source code
blocks, and when being loaded, emacs would exact the Lisp out and
assemble a complete init setting lisp file. If emacs detects that the
configuration org file has been modified, it will automatically
regenerate a new configuration Lisp file before loading.

Most of the code before comes from my previous .emacs file and the
configuration from Daniel Mai on GitHub. use-packages are also
incorporated into this new way of organizing init  files.

* Personal Information
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Yu Liu"
	user-mail-address "yliu193@ford.com")
#+END_SRC* 
* Benchmark Initialization
benchmark-init is used to record the time elapsed to initiate each
package or file. It will help figure out which init task consumes the
most time. 
#+BEGIN_SRC emacs-lisp
(add-to-list 'load-path "~/.emacs.d/elpa/benchmark-init-20150905.238/")
(require 'benchmark-init)
#+END_SRC

* ELPA and MELPA

* Paths


* Packages Loading
* Appearances
* Navigation, Buffer and File Selections
* Spelling
* LaTeX
* Org
* Python
* C
* Key-Bindings
