* Start emacs up really fast (auto start emacs as daemon at start up; then use emacsclientw -c -n to start emacs)
*** In your Emacs/bin directory (where your Emacs binaries are) create a shortcut to runemacs.exe. 
*** You may right-click on file runemacs.exe and choose send-to desktop (create shortcut).
*** Right click on newly created shortcut and choose Properties. In Target put following: "X:\path\to\emacs\bin\runemacs.exe" --daemon , X:\path\to\emacs is your drive letter and path where emacs resides on your harddrive. Close the properties dialog.
*** Press Win+r to open Run dialog and type shell:startup.
*** Copy your newly created link to Emacs server into opened directory. Emacs will start up automatically next time you start the system. Double click on the shortcut to start Emacs server now if it is not already running.
*** In your Emacs/bin directory, create a new shortcut file to emacsclientw.exe. Open Properties for newly created shortcut and in Target "X:\path\to\emacs\bin\emacsclientw.exe" -c -n -a "" 
**** -c tells emacs to create a new frame instead of trying to use the existing frame
**** -n means no wait - don't wait for the server to return
**** -a EDITOR specifies to the emacsclientw.exe which editor to run if emacs.exe is not running. An empty string starts a new server if needed
  -c tells emacs to create a new frame instead of trying to use the existing frame
*** In Open in field, type %Documents% or whatever your choice for default directory is. Close the Properties dialog and rename your shortcut to just: emacs Drag your newly created shortcut to your startbar, or desktop or wherever you wish to have it.
*** No need to edit your .emacs file and add server line to it.

* In Mingw64 terminal, we can add an alias alias e='emacsclientw -n -c -a ""' in .bashrc to ease the typing

* In ubuntu, we can add /usr/bin/emacs --daemon command in "startup" dialog, and a .desktop file should be added automatically in ~/.config/autostart; we can define similar alias e in .bashrc; be patient when turn on computer, wait for daemon to start (it should be started at about the same time as dropbox and psensor -- look for dropbox and temperature icons on the upper right corner, emacs daemon should be ready when those icons are shown.

* We can also add the following line in .bashrc as well: export EDITOR='emacsclient -nc -a ""', so the default editor method is our preferred way.
